SET PAGES 0
SET FEEDBACK OFF
set echo off
set linesize 16000
set pagesize 0
set sqlprompt ''
set trimspool on
set termout off
set headsep off
spool D:\MiniVelos\Sources\Event_Assoc.csv
set markup csv on
SELECT
	EVENT_ID,
	CHAIN_ID,
	EVENT_TYPE,
	NAME,
	NOTES,
	COST,
	COST_DESCRIPTION,
	DURATION,
	USER_ID,
	LINKED_URI,
	FUZZY_PERIOD,
	MSG_TO,
	STATUS,
	DESCRIPTION,
	DISPLACEMENT,
	ORG_ID,
	EVENT_MSG,
	EVENT_RES,
	EVENT_FLAG,
	CREATED_ON,
	PAT_DAYSBEFORE,
	PAT_DAYSAFTER,
	USR_DAYSBEFORE,
	USR_DAYSAFTER,
	PAT_MSGBEFORE,
	PAT_MSGAFTER,
	USR_MSGBEFORE,
	USR_MSGAFTER,
	to_char(STATUS_DT,'DD-MON-YYYY'),
	STATUS_CHANGEBY,
	RID,
	CREATOR,
	LAST_MODIFIED_BY,
	to_char(LAST_MODIFIED_DATE,'DD-MON-YYYY'),
	IP_ADD,
	ORIG_STUDY,
	ORIG_CAL,
	ORIG_EVENT,
	DURATION_UNIT,
	FK_VISIT,
	EVENT_CPTCODE,
	EVENT_FUZZYAFTER,
	EVENT_DURATIONAFTER,
	EVENT_DURATIONBEFORE,
	FK_CATLIB,
	EVENT_CALASSOCTO,
	to_char(EVENT_CALSCHDATE,'DD-MON-YYYY'),
	EVENT_CATEGORY,
	EVENT_SEQUENCE,
	OFFLINE_FLAG,
	HIDE_FLAG,
	EVENT_LIBRARY_TYPE,
	EVENT_LINE_CATEGORY,
	SERVICE_SITE_ID,
	FACILITY_ID,
	FK_CODELST_COVERTYPE,
	BUDGET_TEMPLATE,
	COVERAGE_NOTES,
	FK_CODELST_CALSTAT,
	PATSCH_UPDATE 
FROM ESCH.EVENT_ASSOC;
spool off;
exit