SET PAGES 0
SET FEEDBACK OFF
set echo off
set linesize 6000
set pagesize 0
set sqlprompt ''
set trimspool on
SET TERMOUT OFF
set headsep off
spool D:\MiniVelos\Sources\Person.csv
set markup csv on
SELECT 
  PK_PERSON,
  FK_CODELST_ETHNICITY,
  FK_CODELST_GENDER,
  FK_CODELST_PAT_DTH_CAUSE,
  FK_CODELST_PSTAT,
  FK_CODELST_RACE,
  FK_SITE,
  CAUSE_OF_DEATH_OTHER,
  TO_CHAR(CREATED_ON,'DD-MON-YYYY'),
  CREATOR,
  LAST_MODIFIED_BY,
  TO_CHAR(LAST_MODIFIED_DATE,'DD-MON-YYYY'),
  PAT_FACILITYID,
  PERSON_ADD_ETHNICITY,
  PERSON_ADD_RACE,
  PERSON_CITY,
  PERSON_CODE,
  PERSON_COUNTRY,
  PERSON_COUNTY,
  TO_CHAR(PERSON_DEATHDT,'DD-MON-YYYY'),
  TO_CHAR(PERSON_DOB,'DD-MON-YYYY'),
  PERSON_FNAME,
  PERSON_LNAME,
  PERSON_MNAME,
  PERSON_REGBY,
  TO_CHAR(PERSON_REGDATE,'DD-MON-YYYY'),
  PERSON_STATE,
  PERSON_ZIP,
  PERSON_ADDRESS1 VARCHAR2(100 BYTE),
  PERSON_ADDRESS2 VARCHAR2(100 BYTE)
FROM EPAT.PERSON;
spool off;
exit;
