SET PAGES 0
SET FEEDBACK OFF
set echo off
set linesize 6000
set pagesize 0
set sqlprompt ''
set trimspool on
SET TERMOUT OFF
set headsep off
spool D:\MiniVelos\Sources\Person.csv
set markup csv on
SELECT 
  PK_PERSON,
  FK_CODELST_ETHNICITY,
  FK_CODELST_GENDER,
  FK_CODELST_PAT_DTH_CAUSE,
  FK_CODELST_PSTAT,
  FK_CODELST_RACE,
  FK_SITE,
  CAUSE_OF_DEATH_OTHER,
  CREATED_ON,
  CREATOR,
  LAST_MODIFIED_BY,
  LAST_MODIFIED_DATE,
  PAT_FACILITYID,
  PERSON_ADD_ETHNICITY,
  PERSON_ADD_RACE,
  PERSON_ALTID,
  PERSON_CITY,
  PERSON_CODE,
  PERSON_COUNTRY,
  PERSON_COUNTY,
  PERSON_DEATHDT,
  PERSON_DOB,
  PERSON_FNAME,
  PERSON_LNAME,
  PERSON_MNAME,
  PERSON_PHYOTHER,
  PERSON_REGBY,
  PERSON_REGDATE,
  PERSON_STATE,
  PERSON_ZIP
FROM EPAT.PERSON;
spool off;
exit;