SET PAGES 0
SET FEEDBACK OFF
set echo off
set linesize 16000
set pagesize 0
set sqlprompt ''
set trimspool on
set termout off
set headsep off
spool D:\MiniVelos\Sources\sch_events1.csv
set markup csv on
SELECT
  EVENT_ID,
  OBJECT_ID,
  VISIT_TYPE_ID,
  CHILD_SERVICE_ID,
  SESSION_ID,
  OCCURENCE_ID,
  LOCATION_ID,
  NOTES, 
  TYPE_ID,
  ROLES,
  SVC_TYPE_ID,
  STATUS,
  SERVICE_ID,
  BOOKED_BY,
  ISCONFIRMED,
  DESCRIPTION,
  ATTENDED,
  to_char(START_DATE_TIME,'DD-MON-YYYY'),
  to_char(END_DATE_TIME,'DD-MON-YYYY'),
  BOOKEDON,
  ISWAITLISTED,
  OBJECT_NAME,
  LOCATION_NAME,
  SESSION_NAME,
  USER_NAME,
  PATIENT_ID,
  SVC_TYPE_NAME,
  EVENT_NUM,
  VISIT_TYPE_NAME,
  OBJ_LOCATION_ID,
  FK_ASSOC,
  to_char(EVENT_EXEON,'DD-MON-YYYY'),
  EVENT_EXEBY,
  RID,
  CREATOR,
  LAST_MODIFIED_BY,
  to_char(LAST_MODIFIED_DATE,'DD-MON-YYYY'),
  to_char(CREATED_ON,'DD-MON-YYYY'),
  IP_ADD,
  FK_PATPROT,
  to_char(ACTUAL_SCHDATE,'DD-MON-YYYY'),
  ADVERSE_COUNT,
  VISIT,
  ALNOT_SENT,
  FK_VISIT,
  FK_STUDY,
  EVENT_NOTES,
  EVENT_SEQUENCE,
  SERVICE_SITE_ID,
  FACILITY_ID,
  FK_CODELST_COVERTYPE,
  REASON_FOR_COVERAGECHANGE
FROM ESCH.SCH_EVENTS1;
spool off;
exit